## YAML Template.
---
sil01\VitrineBundle\Entity\Client:
    type: entity
    table: client 
    id:
        id:
            type: integer
            generator: { strategy: AUTO } 

            
            
    