## YAML Template.
---
sil01\VitrineBundle\Entity\Commande:
    type: entity
    table: commande
    id:
        id:
            type: integer
            generator: { strategy: AUTO } 
    fields:
        client:
            type: string
            length: 100
        date:
            type: date
        state:
            type: boolean
    oneToMany:
        ligneDeCommandes:
            mappedBy: commande
            targetEntity: sil01\VitrineBundle\Entity\LigneDeCommande
        

        
            
            