sil01\VitrineBundle\Entity\Patate:
    type: entity
    table: null
    repositoryClass: sil01\VitrineBundle\Repository\PatateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '28'
        sexe:
            type: boolean
    lifecycleCallbacks: {  }
