sil01_vitrine_commande:
    resource: "@sil01VitrineBundle/Resources/config/routing/commande.yml"
    prefix:   /commande
    
sil01_vitrine_client:
    resource: "@sil01VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /client

sil01_vitrine_homepage:
    path:     /index/
    defaults: { _controller: sil01VitrineBundle:Default:accueil }

sil01_vitrine_mentions:
    path:     /mentions/
    defaults: { _controller: sil01VitrineBundle:Default:mentions }

sil01_vitrine_catalogue:
    path:     /catalogue/
    defaults: { _controller: sil01VitrineBundle:Default:catalogue }

sil01_vitrine_articlesParCategorie:
    path: /articlesParCategorie/{id}
    defaults: { _controller: sil01VitrineBundle:Default:articlesParCategorie }
    
sil01_vitrine_contenuPanier:
    path:    /panier/
    defaults: { _controller: sil01VitrineBundle:Panier:contenuPanier }
    
sil01_vitrine_ajoutPanier:
    path:   /panier/ajout/{id}/{quantite}
    defaults: { _controller: sil01VitrineBundle:Panier:ajoutArticle }
    
sil01_vitrine_supprimeArticle:
    path:   /panier/supprimer/{id}/
    defaults: { _controller: sil01VitrineBundle:Panier:supprimeArticle }
    
sil01_vitrine_validationPanier:
    path:   /panier/validation
    defaults: { _controller: sil01VitrineBundle:Panier:validerPanier }
    