<?php

namespace sil01\VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PatateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatateRepository extends EntityRepository
{
}
